### ISSUE TITLE
Grue sounds not working in servers

### ISSUE THREAD

**Issue by ThsHaunted124** [Shinoow/Grue#17] opened 2019-07-22 10:02 UTC
#### Description:
So in singleplayer the warning sounds of grue and the jumpscare sounds work. But when i join my friends server with this mod the sounds dont work.

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Grue: Grue-1.12.2-1.4.0.jar

**Comment by ThexXTURBOXx** [comment] 2019-08-13 10:30
The issue is a bit more complicated than that...
With VanillaFix installed, it even detects some crashes (it crashes once every second):
https://pastebin.com/p4bjRiim

**Comment by Shinoow** [comment] 2019-09-17 17:39
Turns out I missed a minor thing in the 1.12 port, which in turn leads to the sounds not getting registered on the server (no idea how they still managed to get registered on the client). But no, the game doesn't crash, that's VanillaFix overreacting, acting as if the game crashed when in fact all that happened was the client failing to process a network packet from the server (which merely prints that error stack trace in the log).
This will be fixed in the next update.

**Comment by ThexXTURBOXx** [comment] 2019-09-17 17:50
Okay, I already thought, that it's not a "full crash".
So, it really was that minor error I proposed?
Thank you for fixing this!

**Closed** 2019-09-24 17:15 UTC
